package com.nkp.dao;

import com.nkp.pojo.Surl;

public interface SurlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surl
     *
     * @mbggenerated
     */
    int insert(Surl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surl
     *
     * @mbggenerated
     */
    int insertSelective(Surl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surl
     *
     * @mbggenerated
     */
    Surl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Surl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Surl record);
}