package com.nkp.dao;

import com.nkp.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.Date;
import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    UserInfo selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserInfo record);

    UserInfo check(String userName, String userPW);

    List<UserInfo> findAllUser();

    @Select("select * from userInfo where userPhone=#{phone}")
    UserInfo selectByPhone(@Param("phone") String phone);

    List<UserInfo> selLike(@Param("userName") String condition, @Param("type") Integer type, @Param("createTime") Date date);
    @Select("select count(0) from userInfo where userPhone=#{userphone} or userName=#{username}")
    int zc(@Param("username") String username, @Param("userphone") String userphone);
}