package com.nkp.dao;

import com.nkp.pojo.ViewNumber;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface ViewNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewNumber
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewNumber
     *
     * @mbggenerated
     */
    int insert(ViewNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewNumber
     *
     * @mbggenerated
     */
    int insertSelective(ViewNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewNumber
     *
     * @mbggenerated
     */
    ViewNumber selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewNumber
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ViewNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table viewNumber
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ViewNumber record);
    @Select("SELECT * from viewNumber WHERE newsId=#{id}")
    ViewNumber selectByNewsId(int id);
    @Update("UPDATE viewNumber set number=number+1 WHERE newsId=#{id}")
    int newsNumberAdd(int id);
    @Select("SELECT newsId,number from viewNumber ORDER BY number DESC LIMIT 10")
    List<ViewNumber> hb();
}