package com.nkp.dao;

import com.nkp.pojo.Work;
import com.nkp.pojo.WorkWithBLOBs;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.Date;
import java.util.List;

public interface WorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated
     */
    int insert(WorkWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated
     */
    int insertSelective(WorkWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated
     */
    WorkWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WorkWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(WorkWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table work
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Work record);

    WorkWithBLOBs selHave(int id);

    List<WorkWithBLOBs> selLike(@Param("type") Integer type, @Param("city") Integer city, @Param("name") String name, @Param("createTime") Date date);

    //查询所有企业的名称
    @Select("select * from work")
    List<Work> selName();
}