package com.nkp.pojo;

import java.util.Date;

public class Author {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.headPicture
     *
     * @mbggenerated
     */
    private String headpicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.identity
     *
     * @mbggenerated
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.introduce
     *
     * @mbggenerated
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.explain
     *
     * @mbggenerated
     */
    private String explain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.atype
     *
     * @mbggenerated
     */
    private Integer atype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.id
     *
     * @return the value of author.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.id
     *
     * @param id the value for author.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.name
     *
     * @return the value of author.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.name
     *
     * @param name the value for author.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.headPicture
     *
     * @return the value of author.headPicture
     *
     * @mbggenerated
     */
    public String getHeadpicture() {
        return headpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.headPicture
     *
     * @param headpicture the value for author.headPicture
     *
     * @mbggenerated
     */
    public void setHeadpicture(String headpicture) {
        this.headpicture = headpicture == null ? null : headpicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.identity
     *
     * @return the value of author.identity
     *
     * @mbggenerated
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.identity
     *
     * @param identity the value for author.identity
     *
     * @mbggenerated
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.introduce
     *
     * @return the value of author.introduce
     *
     * @mbggenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.introduce
     *
     * @param introduce the value for author.introduce
     *
     * @mbggenerated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.explain
     *
     * @return the value of author.explain
     *
     * @mbggenerated
     */
    public String getExplain() {
        return explain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.explain
     *
     * @param explain the value for author.explain
     *
     * @mbggenerated
     */
    public void setExplain(String explain) {
        this.explain = explain == null ? null : explain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.createTime
     *
     * @return the value of author.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.createTime
     *
     * @param createtime the value for author.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.atype
     *
     * @return the value of author.atype
     *
     * @mbggenerated
     */
    public Integer getAtype() {
        return atype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.atype
     *
     * @param atype the value for author.atype
     *
     * @mbggenerated
     */
    public void setAtype(Integer atype) {
        this.atype = atype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.remarks
     *
     * @return the value of author.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.remarks
     *
     * @param remarks the value for author.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}