package com.nkp.pojo;

import java.util.Date;

public class NewsType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsType.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsType.typeId
     *
     * @mbggenerated
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsType.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsType.creatTime
     *
     * @mbggenerated
     */
    private Date creattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newsType.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsType.id
     *
     * @return the value of newsType.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsType.id
     *
     * @param id the value for newsType.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsType.typeId
     *
     * @return the value of newsType.typeId
     *
     * @mbggenerated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsType.typeId
     *
     * @param typeid the value for newsType.typeId
     *
     * @mbggenerated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsType.name
     *
     * @return the value of newsType.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsType.name
     *
     * @param name the value for newsType.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsType.creatTime
     *
     * @return the value of newsType.creatTime
     *
     * @mbggenerated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsType.creatTime
     *
     * @param creattime the value for newsType.creatTime
     *
     * @mbggenerated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newsType.remarks
     *
     * @return the value of newsType.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newsType.remarks
     *
     * @param remarks the value for newsType.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}