package com.nkp.pojo;

public class Shrio {
    private Surl surl;

    public Surl getSurl() {
        return surl;
    }

    public void setSurl(Surl surl) {
        this.surl = surl;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shrio.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shrio.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shrio.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shrio.id
     *
     * @return the value of shrio.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shrio.id
     *
     * @param id the value for shrio.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shrio.uid
     *
     * @return the value of shrio.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shrio.uid
     *
     * @param uid the value for shrio.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shrio.cid
     *
     * @return the value of shrio.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shrio.cid
     *
     * @param cid the value for shrio.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}