package com.nkp.pojo;

public class WorkWithBLOBs extends Work {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.information
     *
     * @mbggenerated
     */
    private String information;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.aboutUs
     *
     * @mbggenerated
     */
    private String aboutus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.information
     *
     * @return the value of work.information
     *
     * @mbggenerated
     */
    public String getInformation() {
        return information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.information
     *
     * @param information the value for work.information
     *
     * @mbggenerated
     */
    public void setInformation(String information) {
        this.information = information == null ? null : information.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.aboutUs
     *
     * @return the value of work.aboutUs
     *
     * @mbggenerated
     */
    public String getAboutus() {
        return aboutus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.aboutUs
     *
     * @param aboutus the value for work.aboutUs
     *
     * @mbggenerated
     */
    public void setAboutus(String aboutus) {
        this.aboutus = aboutus == null ? null : aboutus.trim();
    }
}